### ISSUE TITLE
很棒又簡易

### ISSUE THREAD

**Issue by longlon651** [transceptor-technology/trender#4]
可惜手機上無法創建是否請前輩可以教授，謝謝您。

**Comment by riklempens** [comment]
I am closing this issue.
Please us English as the main language as this keeps our repositories better readable and allows for easy translation to your native language.

It is perfectly fine to use Google translate or any other translation tool.

---

我正在關閉這個問題。
請使用英語作為主要語言，因為這可以使我們的儲存庫具有更好的可讀性，並且可以輕鬆翻譯為您的母語。

使用Google翻譯或任何其他翻譯工具是完全可以的。

**Comment by longlon651** [comment]
Sorry, I have been busy with my own affairs recently and forgot to come back to read your reply. I will ask questions in English in the future.
